### ISSUE TITLE
Unable to update golden files locally. Build times out after 600 seconds

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1122]
I'm having trouble updating the golden files locally with the steps listed [here](https://github.com/googleapis/gapic-generator-python/blob/64b9ad6e417a15cfbddf0e7a1b57036b8abfc829/DEVELOPMENT.md#integration-tests).

I was able to update golden files previously so something has changed in my environment.

I run the following command in the root of `gapic-generator-python`: 
```
bazel run //tests/integration:asset_update --sandbox_debug
```

however the command times out after 600 seconds with 
```
Error in fail: rules_python_external failed:  (Timed out)
ERROR: <path to gapic generator python>/gapic-generator-python/tests/integration/BUILD.bazel:50:17: //tests/integration:asset_py_gapic depends on //:gapic_plugin in repository @ which failed to fetch. no such package '@gapic_generator_python_pip_deps//': rules_python_external failed:  (Timed out)
```

I've tried the following troubleshooting steps
1) Machine reboot
2) `bazel shutdown` and `sudo rm -rf sudo rm -rf /usr/local/google/home/<user>/.cache/bazel/_bazel_<user>/`
3) `bazel clean --expunge`
4) Fresh clone of `gapic-generator-python`

The strange thing is that I'm still able to use `bazel build` in the root of [googleapis](https://github.com/googleapis/googleapis) to build/generate clients.

cc @vam-google

**Comment by parthea** [comment]
The issue with fetching `rules_python_external` seems to be resolved once I upgrade the bazel build rules [here](https://github.com/googleapis/gapic-generator-python/blob/master/WORKSPACE#L13) to 0.5.0, however now I'm hitting a compile issue with boringssl  that says `with mismatched bound [-Werror=array-parameter=]`

**Comment by arithmetic1728** [comment]
I have the same `with mismatched bound` issue with or without upgrading the `rules_python` build rule.

**Comment by viacheslav-rostovtsev** [comment]
Ok, so Python uses bazel's native `grpc` reference, which is an old version (1.36) and it seems that it contains an old version of `boringssl` which has this issue when building with gcc11.
(I guess that the issue is triggered by our machines upgrading `gcc` on us)

One solution: import grpc directly -- add the following to the top of your `WORKSPACE` (I added after the `rules_python` reference)
```
 http_archive(
     name = "com_github_grpc_grpc",
     urls = ["https://github.com/grpc/grpc/archive/v1.43.0.zip"],
     strip_prefix = "grpc-1.43.0",
 )
```
Second solution is to be more adventurous and supply a `boringssl` to the build process. The folks in this thread https://groups.google.com/g/grpc-io/c/nBjdFT-d1Bo seem to have just the thing -- add this instead of the `com_github_grpc_grpc` import:
(WARNING, not a C developer, whether or not it works will depend on what files are on your machine, but it works for me)
```
new_local_repository(
    name = "boringssl",
    path = "/usr/lib/x86_64-linux-gnu",
    build_file_content = """
cc_library(
  name = "ssl",
  linkopts = ["-lssl", "-lcrypto"],
  visibility = ["//visibility:public"],
)
""",
)
```

I guess the third solution would be to downgrade your gcc but I have not tried it.
