### ISSUE TITLE
Noisy changes appear in autogenerated snippets

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1457]
There is a lot of noise in the generated output, in particular the snippetgen json files, which started about 2 weeks ago where the filenames in the snippetgen json are changing. The issue only appears in clients where we've enabled REST transport. For example in https://github.com/googleapis/python-dataflow, we enabled REST transport in https://github.com/googleapis/python-dataflow-client/pull/139 and the PRs afterwards contained noisy changes

https://github.com/googleapis/python-dataflow-client/pull/141/files
https://github.com/googleapis/python-dataflow-client/pull/143/files

See the screenshot below where the value for `file` is changed from `dataflow_v1beta3_generated_jobs_v1_beta3_aggregated_list_jobs_sync_26f07383.py` to `dataflow_v1beta3_generated_jobs_v1_beta3_aggregated_list_jobs_sync_0d901b38.py`
![image](https://user-images.githubusercontent.com/5184014/191532433-56461dbf-25e7-42f4-ae7b-e664e3cacb79.png)

**Comment by dizcology** [comment]
The issue is caused by samplegen not handling the REST transport type properly, and buckets that with `TRANSPORT_GRPC_ASYNC`: https://github.com/googleapis/gapic-generator-python/blob/main/gapic/samplegen/samplegen.py#L1009. This causes samplegen to later on see two samples (REST and GRPC_SYNC) with the same spec, and is forced to use a hash in the filename.

I think the generated snippets for REST should be different from those for GRPC_SYNC (should specify the REST transport during client instantiation).  At this point it appears that samplegen does not correctly generate REST samples by comparing "sync" samples with hash.  Because of this, we should disable snippet generation for REST until samplegen supports that variant.

I will create a PR for this soon.  @parthea let me know if you have concerns about this.
