### ISSUE TITLE
Update the URL in setup.py to point to the corresponding package in google-cloud-python

### ISSUE THREAD

**Issue by parthea** [googleapis/gapic-generator-python#1543]
The url in `setup.py` should be changed to `https://github.com/googleapis/google-cloud-python/tree/main/packages/<package-name>` to point to the correct homepage for the package in the monorepo.

https://github.com/googleapis/gapic-generator-python/blob/c325a39b86a8b52fcca1ed901cf1c6cadfb61c4e/gapic/templates/setup.py.j2#L41

**Comment by vchudnov-g** [comment]
This seems like a straightforward change, but the all the packages in https://github.com/googleapis/google-cloud-python appear to already have this line set to `url = "https://github.com/googleapis/google-cloud-python"`, both for GAPICs first released in that repo and for GAPICs migrated from split repo. Something is apparently replacing that field already, so we should figure out what that is so that any changes here do not get overwritten.
