### ISSUE TITLE
Lazy loading of types/__init__.py

### ISSUE THREAD

**Issue by BenRKarl** [googleapis/gapic-generator-python#299]
Right now the generator output will not lazy load types imported from types/__init__.py. Is it possible for that file to mirro the logic that exists [here](https://github.com/googleads/google-ads-python/blob/master/google/ads/google_ads/v2/types.py)?

**Comment by software-dov** [comment]
Any `__init__.py` file can provide a lazy-loading interface, it's just a matter of copying the logic into the template. Nor is it particularly difficult, modulo the undefined references issues. It's good to have tracking bugs so that we can clearly identify which `__init__.py` files have yet to be upgraded.

**Comment by software-dov** [comment]
I think this has been solved by tweaked __init__.py layout and construction.
