### ISSUE TITLE
[py] GRPC routing metadata is incorrectly computed for update calls

### ISSUE THREAD

**Issue by bdhess** [googleapis/gapic-generator-python#364]
As an example:
https://github.com/googleapis/google-cloud-python/blob/de73e45a7183a638113153d0faec105cfc437f0e/kms/google/cloud/kms_v1/gapic/key_management_service_client.py#L1569

When the `crypto_key` argument to UpdateCryptoKey is a dict, the attempt to resolve `crypto_key.name` results in an AttributeError ("'dict' object has no attribute 'name'").  The error is caught and ignored, so this fails silently.

Reported by a customer at https://stackoverflow.com/questions/59617920/cant-update-cryptokey-in-us-central1

**Comment by arithmetic1728** [comment]
I think this bug only applies to the monolith generator. The issue is that monolith generator generated code takes individual fields, since one of the field can be either a dict or an object, but the code doesn't handle dict well, it throws exceptions. micro-generator doesn't allow users to provide fields separately, instead they have wrap the fields in a request object, so it won't have this issue.

The following is an example demonstrating this.

micro-generator generated echo method:
```
https://github.com/arithmetic1728/showcase_sample/blob/master/showcase_generated/google/showcase_v1beta1/services/echo/client.py#L140
```

monolith generator generated echo method:
```
https://github.com/arithmetic1728/showcase_sample/blob/fe7abbd8cbde63600c14d7ac1289ee215575ffcf/showcase-monolith/google/showcase_v1beta1/gapic/echo_client.py#L211
```

**Comment by busunkim96** [comment]
This is now resolved for KMS (via migration to the microgenerator)
