### ISSUE TITLE
LRO Silent Failure

### ISSUE THREAD

**Issue by lukesneeringer** [googleapis/gapic-generator-python#9]
Currently, if the LRO annotation is absent but `google.longrunning.Operation` is the response type, it will generate a non-working library. This should become an error.

**Comment by landrito** [comment]
This is slightly incorrect. 

If the LRO annotation is present but the corresponding message type is not found in the file descriptor set, the generated method will simply return the `google.longrunning.Operation` object. This is a silent failure since the library will _generate_ and _work_, but is not generating the library as specified.
