### ISSUE TITLE
Compile a real proto from googleapis/googleapis during tests.

### ISSUE THREAD

**Issue by SurferJeffAtGoogle** [googleapis/gapic-generator-python#904]
We've seen a few bugs like b/187988047.  Even though tests passed, the code generated by the microgenerator failed to compile.  This caused dozens of pull requests with tests failing to be opened in python library repositories.

Please add a test that uses real protos from googleapis/googleapis, and runs `black`, `mypy`, and `flake8` on the output to confirm it compiles.  Using a real API is more likely to catch a generator that generates broken code.

CC @busunkim96 @parthea @vam-google

**Comment by software-dov** [comment]
I think it's definitely desirable to compile all APIs on CI internally. I'm not sure about picking one API as a smoke test; _all_ APIs have been problem children at some point, and picking any one is going to necessarily be arbitrary.
The problem is that we have two parallel, loosely coupled CI and dev systems. It seems likely that any robust solution to bugs like b/187988047 is going to require strengthening the bond between the two systems.

**Comment by software-dov** [comment]
Golden tests added by #905
